import { invoke } from "@tauri-apps/api/core";
import { useParams } from "@solidjs/router";
import { createEffect, createSignal, For, Show } from "solid-js";
import { ViewScaffold } from "./ViewScaffold";

type TranscriptSegment = {
  startMs: number;
  endMs: number;
  text: string;
};

type DocumentDetail = {
  id: string;
  title: string;
  summary: string | null;
  transcript: string;
  audioPath: string | null;
  subtitleSrtPath: string | null;
  subtitleVttPath: string | null;
  durationSeconds: number | null;
  createdAt: string;
  updatedAt: string;
  segments: TranscriptSegment[];
};

function normalizeError(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

function formatTimestamp(milliseconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
}

export function DocumentView() {
  const params = useParams<{ id?: string }>();
  const [document, setDocument] = createSignal<DocumentDetail | null>(null);
  const [isLoading, setIsLoading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);

  createEffect(() => {
    const id = params.id;
    if (!id) {
      setDocument(null);
      setError(null);
      setIsLoading(false);
      return;
    }

    void (async () => {
      setIsLoading(true);
      setError(null);
      try {
        const result = await invoke<DocumentDetail>("get_document", { id });
        setDocument(result);
      } catch (loadError) {
        setError(normalizeError(loadError));
      } finally {
        setIsLoading(false);
      }
    })();
  });

  return (
    <ViewScaffold
      eyebrow="Document"
      title={document()?.title ?? "Document reader"}
      description="Full transcript with timestamped segments and subtitle artifact paths generated by the import pipeline.">
      <section class="space-y-4 rounded-3xl border border-overlay bg-elevation/85 p-6">
        <Show when={!params.id}>
          <p class="rounded-xl border border-overlay bg-surface/40 p-4 text-sm text-subtext">
            Select a document from the library to view transcript details.
          </p>
        </Show>

        <Show when={isLoading()}>
          <p class="text-sm text-subtext">Loading document...</p>
        </Show>

        <Show when={error()}>
          {(message) => (
            <p role="alert" class="rounded-xl border border-accent/50 bg-accent/10 p-3 text-sm text-text">
              {message()}
            </p>
          )}
        </Show>

        <Show when={document()}>
          {(currentDocument) => (
            <>
              <article class="rounded-2xl border border-overlay bg-surface/35 p-4">
                <p class="text-xs text-subtext">Audio path: {currentDocument().audioPath ?? "N/A"}</p>
                <p class="mt-1 text-xs text-subtext">SRT: {currentDocument().subtitleSrtPath ?? "N/A"}</p>
                <p class="mt-1 text-xs text-subtext">VTT: {currentDocument().subtitleVttPath ?? "N/A"}</p>
              </article>

              <article class="rounded-2xl border border-overlay bg-surface/35 p-4">
                <p class="mb-3 text-sm font-semibold text-text">Transcript</p>
                <Show when={currentDocument().segments.length > 0} fallback={<p class="text-sm text-subtext">{currentDocument().transcript}</p>}>
                  <div class="grid gap-2">
                    <For each={currentDocument().segments}>
                      {(segment) => (
                        <div class="rounded-xl border border-overlay/80 bg-elevation/70 px-3 py-2">
                          <p class="text-[11px] font-semibold tracking-[0.14em] text-subtext uppercase">
                            {formatTimestamp(segment.startMs)} - {formatTimestamp(segment.endMs)}
                          </p>
                          <p class="mt-1 text-sm text-text">{segment.text}</p>
                        </div>
                      )}
                    </For>
                  </div>
                </Show>
              </article>
            </>
          )}
        </Show>
      </section>
    </ViewScaffold>
  );
}
